def fourier_data(src, mode):
    maps = {}
    if mode == "kovacs":
        maps.update({
            'period': "gatspy_period",
            'A_1': 'A_1',
            'A_10': 'A_10',
            'A_11': 'A_11',
            'A_12': 'A_12',
            'A_13': 'A_13',
            'A_14': 'A_14',
            'A_15': 'A_15',
            'A_2': 'A_2',
            'A_3': 'A_3',
            'A_4': 'A_4',
            'A_5': 'A_5',
            'A_6': 'A_6',
            'A_7': 'A_7',
            'A_8': 'A_8',
            'A_9': 'A_9',
            'phi_1': 'phi_1',
            'phi_10': 'phi_10',
            'phi_11': 'phi_11',
            'phi_12': 'phi_12',
            'phi_13': 'phi_13',
            'phi_14': 'phi_14',
            'phi_15': 'phi_15',
            'phi_2': 'phi_2',
            'phi_3': 'phi_3',
            'phi_4': 'phi_4',
            'phi_5': 'phi_5',
            'phi_6': 'phi_6',
            'phi_7': 'phi_7',
            'phi_8': 'phi_8',
            'phi_9': 'phi_9'})
    elif mode == "FATS":
        maps.update({
            'period': "PeriodLS",
            "A_1": 'Freq1_harmonics_amplitude_0',
            "A_2": 'Freq1_harmonics_amplitude_1',
            "A_3": 'Freq1_harmonics_amplitude_2',
            "A_4": 'Freq1_harmonics_amplitude_3',
            "A_5": None,
            "A_6": None,
            "A_7": None,
            "A_8": None,
            "A_9": None,
            "A_10": None,
            "A_11": None,
            "A_12": None,
            "A_13": None,
            "A_14": None,
            "A_15": None,
            "phi_1": 'Freq1_harmonics_rel_phase_0',
            "phi_2": 'Freq1_harmonics_rel_phase_1',
            "phi_3": 'Freq1_harmonics_rel_phase_2',
            "phi_4": 'Freq1_harmonics_rel_phase_3',
            "phi_5": None,
            "phi_6": None,
            "phi_7": None,
            "phi_8": None,
            "phi_9": None,
            "phi_10": None,
            "phi_11": None,
            "phi_12": None,
            "phi_13": None,
            "phi_14": None,
            "phi_15": None})
        
    data = {}
    for k, v in maps.items():
        data[k] = src.get(v, 0)
    return data